apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-secrets
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: local-k8s-store
    kind: ClusterSecretStore
  target:
    name: dev-secrets
  data:
    - secretKey: postgres-password
      remoteRef:
        key: dev-secrets
        property: postgres-password
