apiVersion: v1                 # Core Kubernetes API group
kind: Service                  # Defines a Service to expose the pod
metadata:
  name: worker-go              # Service name
  labels:
    app: worker-go             # Label to group with Deployment
spec:
  selector:
    app: worker-go             # Matches pods with this label
  ports:
    - name: http               # Port name (optional but helpful)
      port: 80                 # Port exposed internally in cluster
      targetPort: 8080         # Forwards traffic to containerPort 8080
      protocol: TCP            # Protocol used for this port
