apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-processor
  labels:
    app: async-processor
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-processor
  template:
    metadata:
      labels:
        app: async-processor
        env: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
        - name: async-processor
          image: your-docker-repo/async-processor:latest
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: async-processor-config
                  key: NATS_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: async-processor-config
                  key: LOG_LEVEL
            - name: HTTP_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: async-processor-config
  labels:
    app: async-processor
    env: dev
data:
  NATS_URL: nats://nats:4222
  LOG_LEVEL: info
---
apiVersion: v1
kind: Service
metadata:
  name: async-processor
  labels:
    app: async-processor
    env: dev
spec:
  type: ClusterIP
  selector:
    app: async-processor
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
