apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: messaging
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: 1.1.7
      sourceRef:
        kind: HelmRepository
        name: nats-io
        namespace: messaging
  values:
    replicaCount: 1
    auth:
      enabled: false
    nats:
      jetstream:
        enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats-io
  namespace: messaging
spec:
  url: https://nats-io.github.io/k8s/helm/charts
  interval: 5m
