apiVersion: external-secrets.io/v1beta1    # ESO API version
kind: ExternalSecret                       # Declares an external secret sync
metadata:
  name: mongodb-credentials                # Name of the target K8s Secret
  namespace: storage                       # Namespace where the secret will live
spec:
  refreshInterval: 1h                      # How often to check for updates
  secretStoreRef:
    name: local-k8s-store                  # References the ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: mongodb-credentials              # Name of the resulting K8s Secret
    creationPolicy: Owner                  # ESO will manage the secret lifecycle
  data:
    - secretKey: MONGO_URL                 # Key in the K8s Secret
      remoteRef:
        key: mongodb-url                   # Key in the external source
