apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: incident-demo-secrets
  namespace: incidents
spec:
  secretStoreRef:
    name: local-k8s-store
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: demo-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt_signing_key
      remoteRef:
        key: demo-secrets
        property: jwt_signing_key
